-- Reverse initial schema (development only — wipes all data)
DROP VIEW IF EXISTS v_engagements;
DROP VIEW IF EXISTS v_deliverables;

DROP TRIGGER IF EXISTS trg_audit_blacklist ON blacklist_records;
DROP TRIGGER IF EXISTS trg_audit_feedback ON feedback;
DROP TRIGGER IF EXISTS trg_audit_deliverables ON deliverables;
DROP TRIGGER IF EXISTS trg_audit_engagements ON engagements;
DROP TRIGGER IF EXISTS trg_audit_campaigns ON campaigns;
DROP TRIGGER IF EXISTS trg_audit_contacts ON contacts;
DROP TRIGGER IF EXISTS trg_blacklist_sync ON blacklist_records;
DROP TRIGGER IF EXISTS trg_feedback_after ON feedback;
DROP TRIGGER IF EXISTS trg_deliverable_after ON deliverables;
DROP TRIGGER IF EXISTS trg_engagement_after_status ON engagements;
DROP TRIGGER IF EXISTS trg_engagement_after_insert ON engagements;
DROP TRIGGER IF EXISTS trg_engagement_before ON engagements;
DROP TRIGGER IF EXISTS trg_feedback_touch ON feedback;
DROP TRIGGER IF EXISTS trg_deliverables_touch ON deliverables;
DROP TRIGGER IF EXISTS trg_engagements_touch ON engagements;
DROP TRIGGER IF EXISTS trg_campaigns_touch ON campaigns;
DROP TRIGGER IF EXISTS trg_brands_touch ON brands;
DROP TRIGGER IF EXISTS trg_contacts_touch ON contacts;
DROP TRIGGER IF EXISTS trg_users_touch ON users;

DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS timeline_entries CASCADE;
DROP TABLE IF EXISTS report_share_links CASCADE;
DROP TABLE IF EXISTS monthly_reports CASCADE;
DROP TABLE IF EXISTS registration_submissions CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS deliverables CASCADE;
DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS engagements CASCADE;
DROP TABLE IF EXISTS campaign_managers CASCADE;
DROP TABLE IF EXISTS campaigns CASCADE;
DROP TABLE IF EXISTS brands CASCADE;
DROP TABLE IF EXISTS blacklist_records CASCADE;
DROP TABLE IF EXISTS contact_secondary_categories CASCADE;
DROP TABLE IF EXISTS contact_tags CASCADE;
DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS fn_audit(audit_entity_type) CASCADE;
DROP FUNCTION IF EXISTS fn_blacklist_sync() CASCADE;
DROP FUNCTION IF EXISTS fn_feedback_after() CASCADE;
DROP FUNCTION IF EXISTS fn_deliverable_after() CASCADE;
DROP FUNCTION IF EXISTS fn_engagement_after_status() CASCADE;
DROP FUNCTION IF EXISTS fn_engagement_before() CASCADE;
DROP FUNCTION IF EXISTS fn_refresh_engagement_completion(uuid) CASCADE;
DROP FUNCTION IF EXISTS recompute_contact_summary(uuid) CASCADE;
DROP FUNCTION IF EXISTS recompute_campaign_metrics(uuid) CASCADE;
DROP FUNCTION IF EXISTS fn_engagement_counted(uuid) CASCADE;
DROP FUNCTION IF EXISTS fn_engagement_deliverables_complete(uuid) CASCADE;
DROP FUNCTION IF EXISTS fn_touch_updated_at() CASCADE;

DROP TYPE IF EXISTS audit_entity_type CASCADE;
DROP TYPE IF EXISTS asset_type CASCADE;
DROP TYPE IF EXISTS deliverable_status CASCADE;
DROP TYPE IF EXISTS deliverable_type CASCADE;
DROP TYPE IF EXISTS collaboration_reason CASCADE;
DROP TYPE IF EXISTS interest_level CASCADE;
DROP TYPE IF EXISTS conversation_status CASCADE;
DROP TYPE IF EXISTS campaign_health CASCADE;
DROP TYPE IF EXISTS campaign_status CASCADE;
DROP TYPE IF EXISTS registration_status CASCADE;
DROP TYPE IF EXISTS contact_source CASCADE;
DROP TYPE IF EXISTS classification CASCADE;
DROP TYPE IF EXISTS contact_status CASCADE;
DROP TYPE IF EXISTS contact_type CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
